import React from 'react';

export default {
    FRIST_SCREEN : 'FristScreen',
    LOGIN : 'Login',
    REGIDTER: 'Register',
    OTHER_DETILS: 'OtherDetails',
    HOME: 'Home',
    MEDITATION : 'Meditation',
    MUSIC: 'Music',
    LIVE: 'Live',
    PROFILE: 'Profile',
    USER_CATEGORY_LIST: 'UserCategoryList',
    SUB_CATAGORY_LIST: 'SubCategoryList',
    USER_CATEGORY_DETAIL: 'UserCategoryDetail',
    MUSIC_LIST: 'MusicList',
    MUSIC_PLAYER: 'MusicPlayer',
    SUB_YOGA_LIST: 'SubYogaList',
    YOGA_DETAIL: 'YogaDetail',
    ACTIVITY_LIST:'ActivityCategoryList',
    SUB_ACTIVITY_LIST:'SubActivityCategoryList',
    MAIN_ACTIVITY_LIST:'MainActivityDataList',
    ACTIVITY_DETAIL:'ActivityDatail',
    YOGA_CATEGORY_LIST:'YogaCategoryList',
    YOGA_SUBCATEGORY_LIST:'YogaSubCategoryList',
    YOGA_MAIN_CATEGORY_LIST:'YogaMainCategoryList',
    YOGA_MAIN_DETAIL:'YogaMainDetail',
    YOGA_SUB_SUB_CAT_LIST:'YogaSubSubCatList',
    DIET_LIST:'DietList',

    ADMIN_DASHBOARD:'Admin Dashboard',
    ADMIN_ACTIVITY_LIST:'AdminActivityList',
    ADMIN_ACTIVITY_ADD:'AdminActivityAdd',
    ADMIN_CATEGORY_LIST:'AdminCategoryList',
    ADMIN_CATEGORY_ADD:'AdminCategoryAdd',
    ADMIN_MUSIC_LIST:'AdminMusicList',
    ADMIN_MUSIC_ADD:'AdminMusicAdd',
    ADMIN_YOGA_ADD:'AdminYogaAdd',
    ADMIN_YOGA_LIST:'AdminYogaList',
    ADMIN_CATEGORY_DET_ADD:'AdminCateDetailAdd',
    ADMIN_CATEGORY_DET_LIST:'AdminCategoryDetailList',
    ADMIN_ACTIVITY_DET_ADD:'AdminActivitDetAdd',
    ADMIN_ACTIVITY_DET_LIST:'AdminActivityDetList',
    ADMIN_YOGA_DET_ADD:'AdminYogaDetAdd',
    ADMIN_YOGA_DET_LIST:'AdminYogaDetList',
    ADMIN_MUSIC_DET_ADD:'adminMusicDetAdd',
    ADMIN_MUSIC_DET_LIST:'AdminMusicDetList',
    ADMIN_ACTIVITY_DETAIL_ADD:'AdminActivityDetailAdd',
    ADMIN_DIET_ADD:'AdminDietAdd',
    ADMIN_DIET_LIST:'AdminDietList',
};