export { default as AdminDashboard } from './Dashboard/Dashboard';
export { default as AdminActivityAdd } from './Activity/ActivityAdd/ActivityAdd';
export { default as AdminActivityList } from './Activity/ActivityList/ActivityList';
export { default as AdminCategoryAdd } from './Category/CategoryAdd/CategoryAdd';
export { default as AdminCategoryList } from './Category/CategoryList/CategoryList';
export { default as AdminMusicAdd } from './Music/MusicAdd/MusicAdd';
export { default as AdminMusicList } from './Music/MusicList/MusicList';
export { default as AdminYogaAdd } from './Yoga/YogaAdd/YogaAdd';
export { default as AdminYogaList } from './Yoga/YogaList/YogaList';
export { default as AdminCategoryDetailsList } from './Category/CategoryDetailList/CategoryDetailsList';
export { default as AdminCategoryDetailAdd } from './Category/CategoryDetailAdd/CategoryDetailAdd';
export { default as AdminMusicDetailList } from './Music/MusicDetailList/MusicDetailList';
export { default as AdminYogaDetailList } from './Yoga/YogaDetailList/YogaDetailList';
export { default as AdminActivityDetailList } from './Activity/ActivityDetailList/ActivityDetailList';
export { default as AdminYogaDetailAdd } from './Yoga/YogaDetailAdd/YogaDetailAdd';
export { default as AdminMusicDetailAdd } from './Music/MusicDetailAdd/MusicDetailAdd';
export { default as AdminActivityDetailAdd } from './Activity/ActivityDetailAdd/ActivityDetailAdd'